#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-subsystem-management.adp-kms-access-config-map.name" . }}
  annotations:
  {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
  labels:
  {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
data:
  {{ template "eric-esoa-subsystem-management.obtain-kms-access-script.file-name" . }}: |
{{ .Files.Get .Values.kms.scriptFileName | indent 4}}
