#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}-alarm-polling-config
  labels:
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
data:
  connectivity.check.interval: "60"