#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq .Values.autoScaling.enabled true }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}
  labels:
    app: {{ template "eric-esoa-so-library-chart.name" . }}
    chart: {{ template "eric-esoa-so-library-chart.chart" . }}
{{ include "eric-esoa-so-library-chart.kubernetes-io-info" . | nindent 4 }}
  annotations:
{{ include "eric-esoa-so-library-chart.config-annotations" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "eric-esoa-so-library-chart.name" . }}
  minReplicas: {{ .Values.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
{{- if .Values.autoScaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ .Values.autoScaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end -}}
