#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if gt (.Values.replicaCount | int) 1}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}-pdb
  labels:
    {{ include "eric-esoa-so-library-chart.labels" . | nindent 4 }}
  annotations:
    {{ include "eric-esoa-so-library-chart.annotations" . | nindent 4 }}
spec:
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "eric-esoa-so-library-chart.name" . | quote }}
{{ end }}
