#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $global := fromJson (include "eric-schema-registry-sr.globalMap" .) -}}
{{- if $global.security.policyBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}-psp-bind
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
    ericsson.com/security-policy.capabilities: ""
    ericsson.com/security-policy.type: "restricted/default"
    {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}

roleRef:
  kind: ClusterRole
  name: {{ index $global.security.policyReferenceMap "default-restricted-security-policy" | quote }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-esoa-so-library-chart.name" . }}
{{- end -}}