#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}-{{ template "eric-esoa-subsystem-management.privileged.cluster.role.name" . }}-privileged-policy
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-esoa-subsystem-management.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-esoa-so-library-chart.name" . }}