#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}
  labels:
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}
  labels:
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-esoa-so-library-chart.name" . }}
  labels:
    {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-esoa-so-library-chart.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-esoa-so-library-chart.name" . }}
---
# Explicitly-created secret, referencing the service account created above, which can be mounted by name.
#
# Will be populated with the service account token.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-esoa-subsystem-management.service-account-secret.name" . }}
  annotations:
    "kubernetes.io/service-account.name": {{ template "eric-esoa-subsystem-management.service-account.name" . }}
  {{- include "eric-esoa-so-library-chart.annotations" .| nindent 4 }}
  labels:
  {{- include "eric-esoa-so-library-chart.labels" .| nindent 4 }}
type: kubernetes.io/service-account-token
