#
# COPYRIGHT Ericsson 2023-2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

openapi: 3.0.3
info:
  title: ('deprecated') Adapter Links Service
  description: |
    Adapter Links Service manages pool of adapters which allow for connectivity and interworking between EO-SO Connected Systems. Those adapters are
    specified with unique names. SO allows to retrieve the adapters names as based on a specified subsystem type.

  contact:
    name: ESOA Atlantic Team
    url: 'https://confluence-oss.seli.wh.rnd.internal.ericsson.com/display/ESO/Atlantic'
    email: PDLTEAMATL@pdl.internal.ericsson.com
  license:
    name: Ericsson Copyright License
  version: 1.0.0

tags:
  - name: Read Adapter Links

servers:
  - url: 'http://{hostname}/subsystem-manager/{basePath}'
    variables:
      hostame:
        default: eric-esoa-subsystem-management
      basePath:
        default: v1

paths:
  /subsystems/adapter-links:
    get:
      deprecated: true
      tags:
        - Read Adapter Links
      summary: List all the Adapter Links
      description: Deprecated, use v2/subsystems/adapter-links.
        Gets the list of all the Adapter Links optionally filtered out by the specified subsystem type
      operationId: getAdaptersLinks
      parameters:
        - name: type
          in: query
          required: false
          schema:
            type: string
            default: NFVO
          description: (Optional) specifies the subsystem type to filter the list of adapter links
      responses:
        '200':
          description: Information about adapter link was read successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          $ref: 'responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: 'responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: 'responses.yaml#/components/responses/NotFound'
        '500':
          $ref: 'responses.yaml#/components/responses/InternalServerError'
